config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/signin" => "users/sessions#new", as: "new_user_session"
    post "/signin" => "users/sessions#create", as: "user_session"
    get "/signout" => "users/sessions#destroy", as: "destroy_user_session"
    get "/signup" => "users/registrations#new", as: "new_user_registration"
  end

  devise_for :users, skip: [:sessions], controllers: {
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
  }

  resources :disciplines do
    get 'get_students_for_discipline', to: 'disciplines#get_students_for_discipline'
    get 'edit_students', to: 'disciplines#edit_students'
    post 'update_students', to: 'disciplines#update_students'
  end

  resources :exams do
    get 'edit_assessments', to: 'exams#edit_assessments'
    post 'update_assessments', to: 'exams#update_assessments'
  end

  get 'my_grades', to: 'assessments#get_student_grades'

  resources :users, only: [:index, :edit, :destroy, :update]

  root 'welcome#index'
end

app/models/discipline.rb
class Discipline < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id', required: true
  has_and_belongs_to_many :students, class_name: 'User'
  has_many :exams

  validate :owner_must_be_a_teacher, :ends_date_must_be_after_begins_date
  validates :name, presence: true

  def owner_must_be_a_teacher
    unless owner.present? && owner.has_role?(:teacher)
      errors.add(:owner, 'Le propriétaire d\'une matière ne peut être qu\'un professeur')
    end
  end

  def ends_date_must_be_after_begins_date
    unless beginsOn.present? && endsOn.present? && beginsOn <= endsOn
      errors.add(:beginsOn, 'Le début des interventions ne peut être ultérieur à la fin des interventions')
      errors.add(:endsOn, 'Le début des interventions ne peut être ultérieur à la fin des interventions')
    end
  end
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]

  # GET /disciplines
  def index
    @disciplines = current_user.teached_disciplines
  end

  # returns a json containing an array of all students, with the key 'selected' set to true if the user studies this discipline
  def get_students_for_discipline
    d = Discipline.find(params[:discipline_id])
    students = User.with_role(:student).where(:approved => true).map { |user|
      {
          id: user.id,
          text: user.firstName + ' ' + user.lastName,
          selected: user.studied_disciplines.exists?(d.id)
      }
    }

    render :json => students
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit

  end

  # GET /disciplines/1/edit_students
  def edit_students
    @discipline = Discipline.find(params[:discipline_id])
  end

  # POST /disciplines
  def create
    @discipline = Discipline.new(discipline_params)
    @discipline.owner = current_user

    if @discipline.save
      redirect_to disciplines_path, notice: 'La matière a été crée avec succès.'
    else
      render 'new'
    end
  end

  # PATCH/PUT /disciplines/1
  def update
    if @discipline.update(discipline_params)
      redirect_to disciplines_path, notice: 'La matière a bien été mise à jour.'
    else
      render 'edit'
    end
  end

  def update_students
    d = Discipline.find(params[:discipline_id])
    students = params[:selectedStudentsIds]
    d.students.clear
    d.students = User.find(students) unless students.empty?
    render status: :ok, json: {status: 200}
  end

  # DELETE /disciplines/1
  def destroy
    current_user.teached_disciplines.delete(@discipline)
    redirect_to disciplines_url, notice: 'La matière a bien été supprimée'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary intern  # DELETE /disciplines/1.jsonet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:name, :beginsOn, :endsOn)
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.haml
= bootstrap_form_for(discipline) do |f|
  = render 'layouts/error_messages', object: discipline
  .field
    = f.text_field :name
  .row
    .col-md-6
      .field
        = f.date_select :beginsOn
    .col-md-6
      .field
        = f.date_select :endsOn
  .vertical-spacer-sm
  .actions
    = f.submit "Enregistrer", :class => "btn btn-default";

app/views/disciplines/edit.html.haml
%h1.text-center Edition de la matière
= render 'form', discipline: @discipline
.vertical-spacer-sm
= link_to 'Retour', disciplines_path

app/views/disciplines/edit_students.html.haml
%h1.text-center Inscrire des étudiants pour la matière #{@discipline.name}
.vertical-spacer-sm
%form
  %input#discipline_id{:type => 'hidden', :value => @discipline.id}
  %select{:class => "form-control", :id => "discipline_students", :multiple => "multiple"}

  .vertical-spacer-sm
  .vertical-spacer-sm
  .text-center
    %input#update_discipline_students{class: 'btn btn-primary', type: 'submit', value: 'Enregistrer'}

app/views/disciplines/index.html.haml
%h1.text-center
  Mes matières

.vertical-spacer-sm
.text-center
  = link_to 'Ajouter une matière', new_discipline_path, class: 'btn btn-primary'
.vertical-spacer-sm
.vertical-spacer-sm

%table.table.table-striped
  %thead
    %tr
      %th Nom
      %th Début des interventions
      %th Fin des interventions
      %th Modifier
      %th Supprimer
      %th Gestion des étudiants

  %tbody
    - @disciplines.each do |d|
      %tr
        %td= d.name
        %td= l d.beginsOn
        %td= l d.endsOn
        %td= link_to 'Modifier', edit_discipline_path(d)
        %td= link_to 'Supprimer', discipline_path(d), method: :delete, data: { confirm: 'êtes vous sûr ?' }
        %td= link_to 'Gérer les étudiants', discipline_edit_students_path(d)

app/views/disciplines/new.html.haml
%h1.text-center Creer une matière
= render 'form', discipline: @discipline
.vertical-spacer-sm
= link_to 'Retour', disciplines_path

app/views/disciplines/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @discipline.name
%p
  %strong Beginson:
  = @discipline.beginsOn
%p
  %strong Endson:
  = @discipline.endsOn
%p
  %strong Owner:
  = @discipline.owner
= link_to 'Edit', edit_discipline_path(@discipline)
|
= link_to 'Back', disciplines_path