config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/signin" => "users/sessions#new", as: "new_user_session"
    post "/signin" => "users/sessions#create", as: "user_session"
    get "/signout" => "users/sessions#destroy", as: "destroy_user_session"
    get "/signup" => "users/registrations#new", as: "new_user_registration"
  end

  devise_for :users, skip: [:sessions], controllers: {
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
  }

  resources :disciplines do
    get 'get_students_for_discipline', to: 'disciplines#get_students_for_discipline'
    get 'edit_students', to: 'disciplines#edit_students'
    post 'update_students', to: 'disciplines#update_students'
  end

  resources :exams do
    get 'edit_assessments', to: 'exams#edit_assessments'
    post 'update_assessments', to: 'exams#update_assessments'
  end

  get 'my_grades', to: 'assessments#get_student_grades'

  resources :users, only: [:index, :edit, :destroy, :update]

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!
  def index

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
%style
  body { background: url("#{asset_url('welcome_bg.png')}"); background-size: 100%;}

%div#welcome_page_container
  %h1.title AssessMe
  %h2.title.subtitle La gestion de notes sans prise de tête
  #app-presentation
    %p
      AssessMe est un outil de liaison entre les professeurs et les élèves.
    %p.catchy
      Vous êtes enseignant ?
    %ul
      %li Invitez vos étudiants directement depuis l'application
      %li Gérer vos matières, vos examens et vos notes en toute facilité !
    %p.catchy
      Vous êtes étudiant ?
    %ul
      %li Vous êtes notifié par e-mail dès qu'un enseignant entre votre note
      %li Consultez vos notes n'a jamais été aussi simple !

  .welcome-page-btn
    = link_to 'Connectez-vous', new_session_path('user'), class: 'btn btn-primary btn-lg'
    %br
    %br
    = link_to 'Demandez votre inscription' , new_registration_path('user'), class: 'btn btn-success btn-lg'