config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/signin" => "users/sessions#new", as: "new_user_session"
    post "/signin" => "users/sessions#create", as: "user_session"
    get "/signout" => "users/sessions#destroy", as: "destroy_user_session"
    get "/signup" => "users/registrations#new", as: "new_user_registration"
  end

  devise_for :users, skip: [:sessions], controllers: {
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
  }

  resources :disciplines do
    get 'get_students_for_discipline', to: 'disciplines#get_students_for_discipline'
    get 'edit_students', to: 'disciplines#edit_students'
    post 'update_students', to: 'disciplines#update_students'
  end

  resources :exams do
    get 'edit_assessments', to: 'exams#edit_assessments'
    post 'update_assessments', to: 'exams#update_assessments'
  end

  get 'my_grades', to: 'assessments#get_student_grades'

  resources :users, only: [:index, :edit, :destroy, :update]

  root 'welcome#index'
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :discipline, required: true
  has_many :students, through: :assessments

  validates :title, presence: true

  def self.belonging_to_teacher(t)
    Exam.includes(:discipline).where(discipline: t.teached_disciplines)
        .order('"disciplines"."beginsOn" DESC').references('disciplines.beginsOn')
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  def index
    @exams = Exam.belonging_to_teacher(current_user)
  end

  # GET /exams/1
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit

  end

  def edit_assessments
    @exam = Exam.find(params[:exam_id])
    students_for_exam = @exam.discipline.students

    @assessments = []
    students_for_exam.each { |s|
      @assessments << Assessment.find_or_create_by(student: s, exam: @exam)
    }
  end

  # POST /exams
  def create
    @exam = Exam.new(exam_params)

    if @exam.save
      redirect_to exams_path, notice: 'L\'examen a été créé avec succès.'
    else
      render 'new'
    end
  end

  # PATCH/PUT /exams/1
  def update
    if @exam.update(exam_params)
      redirect_to exams_path, notice: 'L\'examen a bien été mise à jour.'
    else
      render 'edit'
    end
  end

  def update_assessments
    assessments = params[:assessments]
    Assessment.update(assessments.keys, assessments.values)
    redirect_to exam_edit_assessments_path, notice: 'Les notes ont bien été mises à jour.'
  end

  # DELETE /exams/1
  def destroy
    @exam.destroy
    redirect_to exams_url, notice: 'L\'examen a bien été supprimé'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:title, :date, :discipline_id)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.haml
= bootstrap_form_for(exam) do |f|
  = render 'layouts/error_messages', object: exam
  .field
    = f.collection_select(:discipline_id, current_user.teached_disciplines, :id, :name)
  .field
    = f.text_field :title
  .field
    = f.date_select :date
  .actions
    = f.submit

app/views/exams/edit.html.haml
%h1 Modifier l'examen
= render 'form', exam: @exam
.vertical-spacer-sm
= link_to 'Retour', exams_path

app/views/exams/edit_assessments.html.haml
%h1.text-center Edition des notes pour l'examen #{@exam.title} (#{@exam.discipline.name})
.vertical-spacer-sm

- if not @exam.discipline.students.empty?
  = bootstrap_form_tag url: exam_update_assessments_path(@exam.id) do
    %table.table.table-striped
      %thead
        %tr
          %th Etudiant
          %th Note
      %tbody
        - @assessments.each do |a|
          %tr
            %td= a.student.firstName + ' ' + a.student.lastName
            %td= number_field_tag 'assessments[' + a.id.to_s + '][grade]', a.grade, {min: '0', max: '20', class: 'form-control'}

    = button_tag 'Enregistrer', class: 'btn btn-primary'

- else
  %p Aucun étudiant n'est inscrit à la matière #{@exam.discipline.name}...

.vertical-spacer-sm
= link_to 'Inscrire des étudiants à la matière ' + @exam.discipline.name, discipline_edit_students_path(@exam.discipline)
.vertical-spacer-sm
  = link_to 'Retour à la liste des examens', exams_path

app/views/exams/index.html.haml
%h1.text-center
  Mes Examens

.vertical-spacer-sm

.text-center
  = link_to 'Ajouter un examen', new_exam_path, class: 'btn btn-primary'
.vertical-spacer-sm
.vertical-spacer-sm
%table.table.table-striped
  %thead
    %tr
      %th Nom de la matière
      %th Titre de l'examen
      %th Date de l'examen
      %th Gestion des notes
      %th Modifier
      %th Supprimer

  %tbody
    - @exams.each do |e|
      %tr
        %td= e.discipline.name
        %td= e.title
        %td= l e.date
        %td= link_to 'Gérer les notes', exam_edit_assessments_path(e)
        %td= link_to 'Modifier', edit_exam_path(e)
        %td= link_to 'Supprimer', exam_path(e), method: :delete, data: { confirm: 'êtes vous sûr ?' }

app/views/exams/new.html.haml
%h1.text-center Ajouter un examen
.vertical-spacer-sm
= render 'form', exam: @exam
.vertical-spacer-sm
= link_to 'Retour', exams_path

app/views/exams/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @exam.title
%p
  %strong Date:
  = @exam.date
= link_to 'Edit', edit_exam_path(@exam)
|
= link_to 'Back', exams_path